// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Silk.Data;
using Silk.Data.Models;

namespace Silk.Core.Migrations
{
    [DbContext(typeof(SilkDbContext))]
    class SilkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Silk.Core.Database.Models.BlackListedWord", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int>("GuildId")
                    .HasColumnType("integer");

                b.Property<string>("Word")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("GuildId");

                b.ToTable("BlackListedWord");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.GlobalUser", b =>
            {
                b.Property<decimal>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("numeric(20,0)");

                b.Property<int>("Cash")
                    .HasColumnType("integer");

                b.Property<DateTime>("LastCashOut")
                    .HasColumnType("timestamp without time zone");

                b.HasKey("Id");

                b.ToTable("GlobalUsers");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.Guild", b =>
            {
                b.Property<decimal>("Id")
                    .HasColumnType("numeric(20,0)");

                b.Property<string>("Prefix")
                    .IsRequired()
                    .HasMaxLength(5)
                    .HasColumnType("character varying(5)");

                b.HasKey("Id");

                b.ToTable("Guilds");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.GuildConfig", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<bool>("AutoDehoist")
                    .HasColumnType("boolean");

                b.Property<bool>("BlacklistInvites")
                    .HasColumnType("boolean");

                b.Property<bool>("BlacklistWords")
                    .HasColumnType("boolean");

                b.Property<bool>("DeleteMessageOnMatchedInvite")
                    .HasColumnType("boolean");

                b.Property<decimal>("GeneralLoggingChannel")
                    .HasColumnType("numeric(20,0)");

                b.Property<bool>("GreetMembers")
                    .HasColumnType("boolean");

                b.Property<bool>("GreetOnScreeningComplete")
                    .HasColumnType("boolean");

                b.Property<bool>("GreetOnVerificationRole")
                    .HasColumnType("boolean");

                b.Property<decimal>("GreetingChannel")
                    .HasColumnType("numeric(20,0)");

                b.Property<string>("GreetingText")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("GuildId")
                    .HasColumnType("numeric(20,0)");

                b.Property<List<InfractionType>>("InfractionDictionary")
                    .IsRequired()
                    .HasColumnType("integer[]");

                b.Property<string>("InfractionFormat")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("LogMemberJoing")
                    .HasColumnType("boolean");

                b.Property<bool>("LogMessageChanges")
                    .HasColumnType("boolean");

                b.Property<int>("MaxRoleMentions")
                    .HasColumnType("integer");

                b.Property<int>("MaxUserMentions")
                    .HasColumnType("integer");

                b.Property<decimal>("MuteRoleId")
                    .HasColumnType("numeric(20,0)");

                b.Property<bool>("ScanInvites")
                    .HasColumnType("boolean");

                b.Property<bool>("UseAggressiveRegex")
                    .HasColumnType("boolean");

                b.Property<decimal>("VerificationRole")
                    .HasColumnType("numeric(20,0)");

                b.Property<bool>("WarnOnMatchedInvite")
                    .HasColumnType("boolean");

                b.HasKey("Id");

                b.HasIndex("GuildId")
                    .IsUnique();

                b.ToTable("GuildConfigs");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.Infraction", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<decimal>("Enforcer")
                    .HasColumnType("numeric(20,0)");

                b.Property<DateTime?>("Expiration")
                    .HasColumnType("timestamp without time zone");

                b.Property<bool>("HeldAgainstUser")
                    .HasColumnType("boolean");

                b.Property<DateTime>("InfractionTime")
                    .HasColumnType("timestamp without time zone");

                b.Property<int>("InfractionType")
                    .HasColumnType("integer");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<long>("UserDatabaseId")
                    .HasColumnType("bigint");

                b.Property<decimal>("UserId")
                    .HasColumnType("numeric(20,0)");

                b.HasKey("Id");

                b.HasIndex("UserDatabaseId");

                b.ToTable("Infractions");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.Invite", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int?>("GuildConfigId")
                    .HasColumnType("integer");

                b.Property<decimal>("GuildId")
                    .HasColumnType("numeric(20,0)");

                b.Property<string>("VanityURL")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("GuildConfigId");

                b.ToTable("Invite");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.SelfAssignableRole", b =>
            {
                b.Property<decimal>("Id")
                    .HasColumnType("numeric(20,0)");

                b.Property<int?>("GuildConfigId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("GuildConfigId");

                b.ToTable("SelfAssignableRole");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.Ticket", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<DateTime>("Closed")
                    .HasColumnType("timestamp without time zone");

                b.Property<bool>("IsOpen")
                    .HasColumnType("boolean");

                b.Property<DateTime>("Opened")
                    .HasColumnType("timestamp without time zone");

                b.Property<decimal>("Opener")
                    .HasColumnType("numeric(20,0)");

                b.HasKey("Id");

                b.ToTable("Tickets");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.TicketMessage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Message")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("Sender")
                    .HasColumnType("numeric(20,0)");

                b.Property<int>("TicketId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("TicketId");

                b.ToTable("TicketMessage");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.TicketResponder", b =>
            {
                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("ResponderId")
                    .HasColumnType("numeric(20,0)");

                b.ToTable("TicketResponder");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.User", b =>
            {
                b.Property<long>("DatabaseId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int>("Flags")
                    .HasColumnType("integer");

                b.Property<decimal>("GuildId")
                    .HasColumnType("numeric(20,0)");

                b.Property<decimal>("Id")
                    .HasColumnType("numeric(20,0)");

                b.HasKey("DatabaseId");

                b.HasIndex("GuildId");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.BlackListedWord", b =>
            {
                b.HasOne("Silk.Core.Database.Models.GuildConfig", "Guild")
                    .WithMany("BlackListedWords")
                    .HasForeignKey("GuildId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Guild");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.GuildConfig", b =>
            {
                b.HasOne("Silk.Core.Database.Models.Guild", "Guild")
                    .WithOne("Configuration")
                    .HasForeignKey("Silk.Core.Database.Models.GuildConfig", "GuildId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Guild");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.Infraction", b =>
            {
                b.HasOne("Silk.Core.Database.Models.User", "User")
                    .WithMany("Infractions")
                    .HasForeignKey("UserDatabaseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.Invite", b =>
            {
                b.HasOne("Silk.Core.Database.Models.GuildConfig", null)
                    .WithMany("AllowedInvites")
                    .HasForeignKey("GuildConfigId");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.SelfAssignableRole", b =>
            {
                b.HasOne("Silk.Core.Database.Models.GuildConfig", null)
                    .WithMany("SelfAssignableRoles")
                    .HasForeignKey("GuildConfigId");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.TicketMessage", b =>
            {
                b.HasOne("Silk.Core.Database.Models.Ticket", "Ticket")
                    .WithMany("History")
                    .HasForeignKey("TicketId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Ticket");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.User", b =>
            {
                b.HasOne("Silk.Core.Database.Models.Guild", "Guild")
                    .WithMany("Users")
                    .HasForeignKey("GuildId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Guild");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.Guild", b =>
            {
                b.Navigation("Configuration")
                    .IsRequired();

                b.Navigation("Users");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.GuildConfig", b =>
            {
                b.Navigation("AllowedInvites");

                b.Navigation("BlackListedWords");

                b.Navigation("SelfAssignableRoles");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.Ticket", b =>
            {
                b.Navigation("History");
            });

            modelBuilder.Entity("Silk.Core.Database.Models.User", b =>
            {
                b.Navigation("Infractions");
            });
#pragma warning restore 612, 618
        }
    }
}