// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoleMenuPlugin.Database;

#nullable disable

namespace RoleMenuPlugin.Migrations
{
    [DbContext(typeof(RoleMenuContext))]
    [Migration("20220820140303_MenuDescription")]
    partial class MenuDescription
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoleMenuPlugin.Database.RoleMenuModel", b =>
                {
                    b.Property<decimal>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("MaxSelections")
                        .HasColumnType("integer");

                    b.HasKey("MessageId");

                    b.ToTable("RoleMenus");
                });

            modelBuilder.Entity("RoleMenuPlugin.Database.RoleMenuOptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EmojiName")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal[]>("MutuallyExclusiveRoleIds")
                        .IsRequired()
                        .HasColumnType("numeric(20,0)[]");

                    b.Property<decimal[]>("MutuallyInclusiveRoleIds")
                        .IsRequired()
                        .HasColumnType("numeric(20,0)[]");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RoleMenuId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("RoleMenuModelMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleMenuModelMessageId");

                    b.ToTable("RoleMenuOptionModel");
                });

            modelBuilder.Entity("RoleMenuPlugin.Database.RoleMenuOptionModel", b =>
                {
                    b.HasOne("RoleMenuPlugin.Database.RoleMenuModel", null)
                        .WithMany("Options")
                        .HasForeignKey("RoleMenuModelMessageId");
                });

            modelBuilder.Entity("RoleMenuPlugin.Database.RoleMenuModel", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
