// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoleMenuPlugin.Database;

namespace RoleMenuPlugin.Migrations
{
    [DbContext(typeof(RolemenuContext))]
    partial class RolemenuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("RoleMenuPlugin.Database.RoleMenuModel", b =>
                {
                    b.Property<decimal>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("RM_MessageId");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("RM_GuildId");

                    b.HasKey("MessageId");

                    b.ToTable("RoleMenus");
                });

            modelBuilder.Entity("RoleMenuPlugin.Database.RoleMenuOptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RMO_Id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ComponentId")
                        .HasColumnType("text")
                        .HasColumnName("RMO_ComponentId");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("RMO_Description");

                    b.Property<string>("EmojiName")
                        .HasColumnType("text")
                        .HasColumnName("RMO_Emoji");

                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("RMO_GuildId");

                    b.Property<decimal>("MessageId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("RMO_MessageId");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("RMO_RoleId");

                    b.Property<decimal>("RoleMenuId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("RMO_FK");

                    b.Property<decimal?>("RoleMenuModelMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("RoleMenuModelMessageId");

                    b.ToTable("RoleMenuOptionModel");
                });

            modelBuilder.Entity("RoleMenuPlugin.Database.RoleMenuOptionModel", b =>
                {
                    b.HasOne("RoleMenuPlugin.Database.RoleMenuModel", null)
                        .WithMany("Options")
                        .HasForeignKey("RoleMenuModelMessageId");
                });

            modelBuilder.Entity("RoleMenuPlugin.Database.RoleMenuModel", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
